name: Pelican Builder

on:
  push:
    branches: [main]

jobs:
  builddeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Setup environment âŒ›ï¸
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Dependencies ğŸ’»
        run: |
          pip install --no-cache-dir -U pip
          pip install -r requirements.txt
          git clone https://github.com/alexandrevicenzi/Flex.git theme/
          ls theme/Flex
          python -m pip install pelican-render-math    
          python -m pip install pelican-simple-footnotes

      - name: Build ğŸ”§
        run: |
          make publish
      - name: Add nojekyll
        run: |
          touch ./output/.nojekyll
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: output # The folder the action should deploy.
